Cabolt/im1
lanl/NGEE-Arctic-E3SM pull request #4
Opened 2024-05-07 00:15 UTC by chuckaustin

Incorporates an ispolygon flag, a polygontype variable, polygonal-tundra-specific microtopographic parameters, and new routine for calculating inundation fraction in polygonal tundra

2024-05-07 16:46 UTC, rfiorella requested changes
Hi @chuckaustin - a couple small changes that I was wondering if you could make before I merge this. Let me know if you have any questions.

2024-05-07 16:46 UTC, rfiorella commented on components/elm/src/main/landunit_varcon.F90
@chuckaustin  This file needs a few updates - the set_polygon_names subroutine will need two additional variables to be defined, similar to what is provided on L. 36 and 37 for the set_landunit_names subroutine. You can just push another commit to your branch and it will be reflected in this PR.

2024-05-07 16:46 UTC, rfiorella commented on components/elm/src/data_types/LandunitType.F90
check indentations in this file

2024-05-07 16:46 UTC, rfiorella commented on components/elm/src/biogeophys/CanopyHydrologyMod.F90
a few minor indentation changes needed on this file - L. 841-842, 857-859, 864-877

2024-05-07 20:00 UTC, chuckaustin commented on components/elm/src/data_types/LandunitType.F90
Fixed

2024-05-07 20:01 UTC, chuckaustin commented on components/elm/src/biogeophys/CanopyHydrologyMod.F90
Fixed (I think)

2024-05-07 20:03 UTC, chuckaustin commented on components/elm/src/main/landunit_varcon.F90
Thanks Rich, think I fixed this. Does set_polygon_names need to be called anywhere in the file (for example, like how set_landunit_names is called in line 84, in the landunit_varcon_init subroutine)?

2024-05-08 04:06 UTC, rfiorella commented on components/elm/src/main/landunit_varcon.F90
That's a good question - not sure, but my hunch is yes otherwise I don't think this new subroutine will ever be called. I'd say let's add it and then we can always remove it later if it's not needed.

2024-05-08 04:16 UTC, rfiorella commented on components/elm/src/biogeophys/CanopyHydrologyMod.F90
Close I think! The log file here: https://github.com/lanl/NGEE-Arctic-E3SM/actions/runs/8991525073/job/24699336871 suggests there are still some issues here with the `do` and `if` loops. (e.g., line 861 and 877 are not needed)

2024-05-10 14:25 UTC, rfiorella approved these changes

2024-05-10 14:26 UTC, merged